In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# 1.Plotly中的graph_objects和express
Plotly是一个用于制作可视化图表的Python库。它提供了两个主要的子库：graph_objects和express。

graph_objects提供了更灵活的图表制作方式，这意味着你可以更好地控制每个元素的外观和样式。它支持多种类型的图表，例如散点图、条形图、气泡图和3D图表等。graph_objects使得创建高度可定制的图表变得轻而易举，对于需要高度自定义图表的使用者来说非常有用。

而express则提供了更简单的图表制作方式。它提供了一组方便的方法，可以帮助你快速创建通用的图表，例如线图、柱状图和散点图等。express适合那些希望快速创建美丽图表的用户，它极大地简化了制作图表的过程。

# 2.Scipy.stats
Scipy.stats是一个用于统计分析的Python库，它包含了各种用于概率分布、假设检验、回归分析和描述统计学等的函数。这些函数被广泛应用于工程、科学和社会学等领域。通过SciPy.stats，你可以进行诸如t检验、卡方检验、F检验等常见的统计分析过程，这对于需要进行数据分析和统计建模的用户来说非常有用。

# 3.IPython.display
IPython.display是一个用于在Jupyter Notebook中显示内容的Python库。它提供了一组用于在Notebook中显示各种内容的函数，包括文本、图像、HTML和多媒体内容等。IPython.display适合那些希望将复杂的分析结果以可视化方式展现给用户的人。例如，你可以使用它在Notebook中显示某个图表、某个视频或者某个动画等，这可以使得分析结果更加生动形象。

In [2]:
import plotly.graph_objects as go
import plotly.express as px
import scipy.stats as stats
from IPython.display import display, HTML

In [3]:
#import data
df = pd.read_csv('kaggle/input/house-prices-advanced-regression-techniques/train.csv')

In [4]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [5]:
#Function to create scrollable table within a small window
def create_scrollable_table(df, table_id, title):
    html = f'<h3>{title}</h3>'
    html += f'<div id="{table_id}"style="height:200px; overflow:auto;">'
    html += df.to_html()
    html += '</div>'
    return html

In [6]:
numerical_features = df.select_dtypes(include=[np.number])
numerical_features.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

  select_dtypes(include=[np.number])这一部分使用了include参数来选择数据框中的数值型特征。np.number代表numpy库中的数值类型。通过这个操作，numerical_features将会是一个只包括**数值型**特征的子集。
  
  .describe()函数应用在numerical_features上，用于生成描述性统计信息。describe()默认会计算每列数据的统计指标，包括计数、均值、标准差、最小值、25%分位数、中位数(50%分位数)、75%分位数和最大值。这些统计指标可以帮助你了解**每个数值型特征的分布情况、中心趋势和离散程度**

In [7]:
#Summary statistics for numerical features
summary_stats = numerical_features.describe().T
html_numerical = create_scrollable_table(summary_stats, 'numerical_features', 'Summary statistics for numerical features')
display(HTML(html_numerical))

describe().T被应用在numerical_features上，生成了数值型特征的描述性统计信息。.T表示对结果进行转置操作，使得每个特征在行上，统计指标在列上。

create_scrollable_table是一个自定义函数，用于创建可滚动的表格。它接受三个参数：描述性统计结果（summary_stats）、表格标题（'numerical_features'）和表格描述（'Summary statistics for numerical features'）。它会生成一个含有滚动功能的HTML表格。

display(HTML(html_numerical))的作用是显示生成的HTML表格，其中html_numerical包含了表格的相关HTML代码。

In [8]:
#Summary statistics for categorical features
categorical_features = df.select_dtypes(include=[object])
cat_summary_stats = categorical_features.describe().T
html_categorical = create_scrollable_table(cat_summary_stats, 'categorical_features',
                                         'Summary statistics for categorical')
display(HTML(html_categorical))

  select_dtypes(include=[object])这一部分使用了include参数来选择数据框(df)中的分类特征。object表示Python中的字符串类型，通常用于表示**分类变量**。通过这个操作，categorical_features将会是一个只包括**分类特征**的子集。
  
  .describe().T函数被应用在categorical_features上，生成了分类特征的描述性统计信息。.T表示对结果进行转置操作，使得每个特征在行上，统计指标在列上

In [9]:
#Null values in the dataset
null_values = df.isnull().sum()
html_null_values = create_scrollable_table(null_values.to_frame(), 'null values',
                                          'Null values in the dataset')

#Percentage of missing values for each feature
missing_percentage = (df.isnull().sum()/len(df)) * 100
html_missing_percentage = create_scrollable_table(missing_percentage.to_frame(),
                                                 'missing_percentage',
                                                 'Percentage of missing')
display(HTML(html_null_values + html_missing_percentage))

isnull().sum()函数被应用在数据框(df)上，返回每个特征中缺失值的数量。这是一个Series对象，其中每个特征都被视为索引，其值为该特征的缺失值数量。

to_frame()函数被应用在null_values上，将其转换为DataFrame对象。

(df.isnull().sum()/len(df)) * 100计算每个特征中缺失值的百分比，生成了每个特征中缺失值的百分比信息

to_frame()函数被应用在missing_percentage上，将其转换为DataFrame对象。

In [10]:
#Exploring rows with missing values
rows_with_missing_values = df[df.isnull().any(axis=1)]
html_rows_with_missing_values = create_scrollable_table(rows_with_missing_values.head(),
                                                 'rows_with_missing_values',
                                                 'Rows with missing values')
display(HTML(html_rows_with_missing_values))

df.isnull().any(axis=1)函数被应用在数据框(df)上，返回一个布尔Series对象，表示每一列是否存在缺失值。any(axis=1)的参数设置为1，表示沿着列的方向检查是否有任何一个元素为真（即是否存在缺失值）

df[df.isnull().any(axis=1)]将会筛选出数据集中存在缺失值的列，返回一个新的数据框，其中只包含具有缺失值的列

head()函数被应用在rows_with_missing_values上，返回新数据框中的前几行，默认为5行

In [11]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [12]:
# Fit a normal distribution to the SalePrice data
mu, sigma = stats.norm.fit(df['SalePrice'])

#Create a histogram of the ScalePrice columns
hist_data = go.Histogram(x=df['SalePrice'],nbinsx=50,name='Histogram',opacity=0.75,
                              histnorm='probability density',marker=dict(color='purple'))

#Calculate the normal distribution based on the fitted parameters
x_norm = np.linspace(df['SalePrice'].min(), df['SalePrice'].max(), 100)
y_norm = stats.norm.pdf(x_norm, mu, sigma)

#Create the normal distribution overlay
norm_data = go.Scatter(x=x_norm, y=y_norm, mode='lines', name=f"Normal dist. (µ={mu:.2f}, σ={sigma:.2f})", line=dict(color="green"))

#Create the normal distribution overlay
fig = go.Figure(data=[hist_data, norm_data])

#Set the layout for the plot
fig.update_layout(title="SalePrice Distribution",
                 xaxis_title='SalePrice',
                 yaxis_title='Density',
                 legend_title_text='Fitted Normal Distribution',
                 plot_bgcolor='rgba(32,32,32,1)',
                 paper_bgcolor='rgba(32,32,32,1)',
                 font=dict(color='white')
                 )

#Fit a normal distribution to the SalePrice data

  通过stats.norm.fit()函数来对df['SalePrice']列进行正态分布拟合，返回拟合后分布的均值和标准差，即mu和sigma

#Create a histogram of the ScalePrice columns

  使用go.Histogram()函数创建一个直方图，其中x参数为要画直方图的数据列（这里是df['SalePrice']），nbinsx表示直方图的条数，histnorm='probability density'参数表示要以概率密度函数的形式画出直方图，opacity表示图表的透明度，name是该直方图在图例中显示的名称，marker参数可用于设置图表的颜色、大小等。

#Calculate the normal distribution based on the fitted parameters

  通过np.linspace()函数生成一组等间隔的数字，作为横坐标。使用stats.norm.pdf()函数计算在这组数字上的正态分布的概率密度函数值，并将其存储到y_norm变量中

#Create the normal distribution overlay

  使用go.Scatter()函数创建一个散点图，其中x参数为之前生成的等间隔数字，y参数为计算得到的概率密度函数值，mode='lines'表示要以线条的形式绘制，name是该线条在图例中显示的名称，line参数可用于设置线条的颜色、宽度等

#Create the normal distribution overlay

  go.Figure()函数将直方图和概率密度函数图合并成一个图表，并将其存储到fig变量中

#Set the layout for the plot

  fig.update_layout()函数用于更新图表的布局。title参数设置图表的标题为"SalePrice Distribution"，xaxis_title参数设置横坐标的标签为"SalePrice"，yaxis_title参数设置纵坐标的标签为"Density"，legend_title_text参数设置图例标题为"Fitted Normal Distribution"。

  plot_bgcolor参数和paper_bgcolor参数分别设置图表的绘图区域和整个图表的背景颜色为黑色（RGBA颜色表示为"rgba(32,32,32,1)"）。font参数设置图表中文本的颜色为白色。

In [13]:
#Create a Q-Q plot
qq_data = stats.probplot(df['SalePrice'], dist='norm')
qq_fig = px.scatter(x=qq_data[0][0], y=qq_data[0][1], labels={'x': 'Theoretical Quantiles', 'y':'Ordered Values'}, color_discrete_sequence=['purple'])
qq_fig.update_layout(title='Q-Q plot',
                    plot_bgcolor='rgba(32, 32, 32, 1)',
                    paper_bgcolor='rgba(32, 32, 32, 1)',
                    font=dict(color='white')
                    )

#Calculate the line of best fit
slope, intercept, r_value, p_value, std_err = stats.linregress(qq_data[0][0], qq_data[0][1])
line_x = np.array(qq_data[0][0])
line_y = intercept + slope * line_x

#Add the line of beat fit to the Q-Q plot
line_data = go.Scatter(x=line_x, y=line_y, mode='lines', name='Normal Line', line=dict(color='green'))

#Update the Q-Q plot with the normal line
qq_fig.add_trace(line_data)

#Show the plots
fig.show()
qq_fig.show()

stats.probplot()函数用于生成Q-Q plot。其中，df['SalePrice']作为输入数据，dist='norm'参数表示使用正态分布作为比较标准。

px.scatter()函数用于生成散点图，其中x参数为理论量化值，y参数为排序后的实际值。此外，labels参数用于设置x轴和y轴的标签，color_discrete_sequence参数可用于设置散点图的颜色。

使用stats.linregress()函数计算适合数据的最佳拟合直线，然后使用go.Scatter()函数生成该直线的散点图，并将其添加到原始Q-Q plot图表中，再次使用update_layout()函数对图表进行设置，并使用qq_fig.show()显示结果

通过以上步骤，可以更多地了解数据与正态分布的偏离程度，并验证该数据是否符合正态分布。

在生成Q-Q plot时，我们将实际观测值的排序顺序（即横坐标）与对应的理论量化值的排序顺序（即纵坐标）进行比较。如果数据符合所选择的分布函数，则这些点应该沿着一条直线分布。如果数据偏离了这条直线，则可能表明数据可能不符合所选择的分布函数。

In [14]:
#1.Distribution of dwelling types and relation to saleprices
dwelling_types = df['BldgType'].value_counts()
dwelling_prices = df.groupby('BldgType')['SalePrice'].mean()

#Format labels for the second graph
formatted_dwelling_prices = ['$' + f'{value:,.2f}' for value in dwelling_prices.values]

#Create bar charts
fig1 = go.Figure(data=[go.Bar(x=dwelling_types.index,
                             y=dwelling_types.values,
                             marker_color='rgb(76,175,80)',
                             text=dwelling_types.values,
                             textposition='outside',
                             width=0.4,
                             marker=dict(line=dict(width=2, color='rgba(0,0,0,1)'),opacity=1)
                             )])
fig1.update_layout(title='Distribution of Building Types',
                  xaxis_title='Buliding Type',
                  yaxis_title='Count',
                  plot_bgcolor='rgba(34, 34, 34, 1)',
                  paper_bgcolor='rgba(34, 34, 34, 1)',
                  font=dict(color='white')
                  )
fig2 = go.Figure(data=[go.Bar(x=dwelling_prices.index,
                             y=dwelling_prices.values,
                             marker_color='rgb(156,39,176)',
                             text=formatted_dwelling_prices,
                             textposition='outside',
                             width=0.4,
                             marker=dict(line=dict(width=2, color='rgba(0,0,0,1)'),opacity=1)
                             )])
fig2.update_layout(title='Average Sale Price by Building Type',
                  xaxis_title='Building Type',
                  yaxis_title='Price',
                  plot_bgcolor='rgba(34,34,34,1)',
                  paper_bgcolor='rgba(34,34,34,1)',
                  font=dict(color='white')
                  )
#show the figures
fig1.show()
fig2.show()

对DataFrame中'BldgType'列的值进行计数，并将计数结果存储在'dwelling_types'变量中。它会统计每种建筑类型出现的次数。

对'DataFrame'根据建筑类型('BldgType')进行分组，然后计算每个建筑类型对应的'SalePrice'列的均值，并将结果存储在'dwelling_prices'变量中。它会得到每个建筑类型的平均销售价格。

对'dwelling_prices'中的每个价格值进行格式化，添加货币符号和两位小数，并将格式化后的字符串存储在'formatted_dwelling_prices'列表中。例如，如果一个价格值为100000，它将被格式化为"$100,000.00"。

创建了一个柱状图对象(fig1)，使用Plotly库的Bar函数。它将建筑类型作为X轴的标签，建筑类型数量作为Y轴的值。通过设置颜色、文字位置、宽度和边框等参数，美化了柱状图的显示效果。

设置柱状图(fig1)的布局和样式。它设置了图表的标题、X轴和Y轴的标题，以及图表的背景颜色和字体颜色等。

创建了另一个柱状图对象(fig2)，用于展示不同建筑类型的平均销售价格。它的设置与之前的柱状图类似，只是X轴的标签换成了建筑类型的平均销售价格。

这行代码用于设置柱状图(fig2)的布局和样式，具体设置与之前的柱状图类似。

第一个图表显示了不同建筑类型的数量分布，可以帮助我们了解不同类型房屋的数量占比情况。通过直观地比较柱状图的高度，我们可以得知哪种类型的房屋数量最多，哪些类型的房屋数量较少。

第二个图表展示了不同建筑类型的平均销售价格，有助于我们比较各种建筑类型的房屋价格水平。通过柱状图的高度，我们可以直观地了解每种建筑类型的平均销售价格，从而判断哪种类型的房屋价格较高或较低。

In [15]:
#2.Zoning impact on sale price
zoning_prices = df.groupby('MSZoning')['SalePrice'].mean()
fig3 = px.bar(x=zoning_prices.index, y=zoning_prices.values,
             title='Averge Sale Price by Zoning',
             color_discrete_sequence=['purple', 'green'],text=zoning_prices.values,
             template='plotly_dark')
fig3.update_traces(texttemplate='$%{text:,.0f}',textposition='outside')
fig3.update_yaxes(title='Sale Price', tickprefix='$', tickformat=',')
fig3.update_xaxes(title='Zoning')
fig3.update_layout(uniformtext_minsize=8, uniformtext_mode='hide')

fig3.show()

将数据集 df 按照 MSZoning 分组，并计算每个分组中 SalePrice 的平均值，得到一个名为 zoning_prices 的 Pandas Series。

使用 plotly.express 库创建一个条形图 fig3。x 参数为 zoning_prices.index，即区域名称；y 参数为 zoning_prices.values，即平均房价；title 参数为图表的标题；color_discrete_sequence 参数用于设置颜色序列；text 参数为条形上显示的文本，这里为平均房价的值；template 参数用于指定图表样式模板

使用 update_traces() 方法对 fig3 中的每一个条形进行设置，包括设置文本模板、文本位置等。

使用 update_yaxes() 和 update_xaxes() 方法分别对 Y 轴和 X 轴进行设置，包括设置坐标轴标题、坐标轴刻度格式等。

使用 update_layout() 方法对图表整体进行设置，包括设置均匀文本最小字号和文本模式。

这段代码主要是通过使用 Pandas 分组计算数据集中不同区域的平均房价，并使用 Plotly 库绘制条形图展示不同区域的平均房价。

In [16]:
# 3. Street and alley access types effect on sale price
street_prices = df.groupby('Street')['SalePrice'].mean()
alley_prices = df.groupby('Alley')['SalePrice'].mean()

# Street Prices
colors_street = np.where(street_prices.index == 'Pave', 'purple', 'green')
fig5 = px.bar(x=street_prices.index, y=street_prices.values, title='Average Sale Price by Street Type',
              template='plotly_dark', text=street_prices.values,
              color=colors_street, color_discrete_sequence=['purple', 'green'])

fig5.update_traces(texttemplate='$%{text:,.0f}', textposition='outside')
fig5.update_yaxes(title='Sale Price', tickprefix='$', tickformat=',')
fig5.update_xaxes(title='Street Type')
fig5.update_layout(showlegend=False)

# Alley Prices
colors_alley = np.where(alley_prices.index == 'Pave', 'purple', 'green')
fig6 = px.bar(x=alley_prices.index, y=alley_prices.values, title='Average Sale Price by Alley Type',
              template='plotly_dark', text=alley_prices.values,
              color=colors_alley, color_discrete_sequence=['purple', 'green'])

fig6.update_traces(texttemplate='$%{text:,.0f}', textposition='outside')
fig6.update_yaxes(title='Sale Price', tickprefix='$', tickformat=',')
fig6.update_xaxes(title='Alley Type')
fig6.update_layout(showlegend=False)

fig5.show()
fig6.show()

使用 Pandas 的 groupby() 方法计算不同街道类型（Street）的平均房价，得到一个名为 street_prices 的 Pandas Series。同样地，使用 groupby() 方法计算不同小巷类型（Alley）的平均房价，得到一个名为 alley_prices 的 Pandas Series。

使用 Plotly 库创建两个条形图 fig5 和 fig6。x 参数分别为街道类型和小巷类型；y 参数分别为对应的平均房价；title 参数分别为图表的标题；template 参数用于指定图表样式模板；text 参数为条形上显示的文本，这里为平均房价的值；color 和 color_discrete_sequence 参数用于设置颜色

使用 update_traces() 方法对每个图中的条形进行设置，包括设置文本模板和文本位置。

使用 update_yaxes() 和 update_xaxes() 方法分别对 Y 轴和 X 轴进行设置，包括设置坐标轴标题、坐标轴刻度格式等。

使用 update_layout() 方法对图表整体进行设置，包括隐藏图例。

In [17]:
# 4. Average sale price by property shape
colors = px.colors.qualitative.Plotly

shape_prices = df.groupby('LotShape')['SalePrice'].mean()
contour_prices = df.groupby('LandContour')['SalePrice'].mean()
# Shape Prices
fig7 = px.bar(x=shape_prices.index, y=shape_prices.values, title='Average Sale Price by Property Shape',
              template='plotly_dark', text=shape_prices.values)

fig7.update_traces(marker_color=colors, texttemplate='$%{text:,.0f}', textposition='outside')
fig7.update_yaxes(title='Sale Price', tickprefix='$', tickformat=',')
fig7.update_xaxes(title='Property Shape')
fig7.update_layout(showlegend=False)

# Contour Prices
fig8 = px.bar(x=contour_prices.index, y=contour_prices.values, title='Average Sale Price by Property Contour',
              template='plotly_dark', text=contour_prices.values)

fig8.update_traces(marker_color=colors, texttemplate='$%{text:,.0f}', textposition='outside')
fig8.update_yaxes(title='Sale Price', tickprefix='$', tickformat=',')
fig8.update_xaxes(title='Property Contour')
fig8.update_layout(showlegend=False)

fig7.show()
fig8.show()

In [18]:
# 5. Calculate Property Age
df['PropertyAge'] = df['YrSold'] - df['YearBuilt']

# Calculate Correlation between Property Age and Sale Price
age_price_corr = df['PropertyAge'].corr(df['SalePrice'])
print(f'Correlation between Property Age and Sale Price: {age_price_corr}')

# Create a scatter plot to visualize the relationship between Property Age and Sale Price
fig9 = px.scatter(df, x='PropertyAge', y='SalePrice', title='Property Age vs Sale Price', color='PropertyAge', color_continuous_scale=px.colors.sequential.Purp)

fig9.update_layout(plot_bgcolor='rgb(30,30,30)', paper_bgcolor='rgb(30,30,30)', font=dict(color='white'))

fig9.show()

Correlation between Property Age and Sale Price: -0.523350417546816

使用Pandas的groupby()方法，计算了根据物业形状和地势轮廓进行分组后的平均售价，分别存储在shape_prices和contour_prices中。

创建了两个条形图fig7和fig8。x参数分别为物业形状和地势轮廓，y参数分别为对应的平均售价，title参数分别为图表的标题，template参数用于指定图表的样式模板，text参数为条形上显示的文本，这里为平均售价的值

通过这些图表，可以直观地比较不同物业形状和地势轮廓对平均售价的影响情况。

In [19]:
# 6. Calculate Correlation between Living Area and Sale Price
living_area_price_corr = df['GrLivArea'].corr(df['SalePrice'])
print(f'Correlation between Living Area (above grade) and Sale Price: {living_area_price_corr}')

# Create a scatter plot to visualize the relationship between Living Area and Sale Price
fig10 = px.scatter(df, x='GrLivArea', y='SalePrice', title='Living Area (above grade) vs Sale Price', color='GrLivArea', color_continuous_scale=px.colors.sequential.Purp)

fig10.update_layout(plot_bgcolor='rgb(30,30,30)', paper_bgcolor='rgb(30,30,30)', font=dict(color='white'))

fig10.show()

Correlation between Living Area (above grade) and Sale Price: 0.7086244776126521

使用corr()方法计算了生活面积和售价之间的相关系数，将结果存储在living_area_price_corr变量中。

调用px.scatter()函数创建了一个散点图fig10。其中，x参数为生活面积，y参数为售价，title参数为图表的标题，color参数为生活面积（GrLivArea）用于给点添加颜色，color_continuous_scale参数设置颜色渐变的色谱类型（这里使用了紫色调的色谱）

代码中的print()语句用于打印生活面积与售价之间的相关系数。

通过散点图可以直观地观察到生活面积与售价之间的趋势和关系，相关性系数则提供了一个数值上的度量。

In [20]:
# 7. Box plot of price over the years
yearly_avg_sale_price = df.groupby('YrSold')['SalePrice'].mean()

fig13 = px.box(df, x='YrSold', y='SalePrice', title='Sale Price Trends Over the Years',
               points=False, color_discrete_sequence=['green'])

fig13.add_trace(px.line(x=yearly_avg_sale_price.index, y=yearly_avg_sale_price.values).data[0])

fig13.update_traces(line=dict(color='purple', width=4), selector=dict(type='scatter', mode='lines'))

for year, avg_price in yearly_avg_sale_price.items():
    fig13.add_annotation(
        x=year,
        y=avg_price,
        text=f"{avg_price:,.0f}",
        font=dict(color='white'),
        showarrow=False,
        bgcolor='rgba(128, 0, 128, 0.6)'
    )

fig13.update_layout(
    plot_bgcolor='rgb(30,30,30)',
    paper_bgcolor='rgb(30,30,30)',
    font=dict(color='white'),
    xaxis_title='Year Sold',
    yaxis_title='Sale Price'
)

fig13.show()

使用groupby()方法按照年份（YrSold）计算了每年的平均售价，并将结果存储在yearly_avg_sale_price中。

调用px.box()函数创建了一个箱线图fig13。其中，x参数为年份，y参数为售价，title参数为图表的标题，points参数设置为False以隐藏异常值点，color_discrete_sequence参数设置箱线的颜色为绿色

调用px.line()函数创建了一条折线图，用来表示每年的平均售价变化趋势。通过.data[0]获取折线图的数据，并将其添加到箱线图中。

调用update_traces()方法对折线进行设置，包括设置颜色为紫色、宽度为4。

使用for循环遍历每个年份和平均售价，在图表中添加了注释，显示每个年份对应的平均售价，并自定义了注释的样式。

通过这个箱线图，可以看出不同年份的售价分布情况和趋势，同时折线图则突出了平均售价的变化趋势。

中位数（Median）：箱线图中的中间线代表了数据的中位数，即将数据按升序排列后位于中间位置的值。它表示了整体数据的中心趋势。

箱体（Box）：箱体由上下两条边界线包围，代表了数据的四分位数（quartiles）。箱体的上边界表示75%的数据落在该值之下，下边界表示25%的数据落在该值之上。箱体的高度反映了数据的离散程度。

上限和下限（Whiskers）：箱线图上下两端的线段被称为“须”或“whiskers”。它们延伸至数据中的最大和最小非异常值，用于表示数据的范围。

异常值（Outliers）：箱线图中的圆点或其他符号表示的数据点被认为是异常值。它们远离箱体和须线，可能代表了与其他数据点显著不同的观测结果。

举个例子来解读箱线图：假设在某个年份的箱线图中，箱体较低位置的边界线大约在10万美元，较高位置的边界线大约在20万美元，中位数位于箱体的中间位置，即15万美元。须线的上限延伸至30万美元，下限延伸至5万美元，表示了数据的范围。此外，图中有几个圆点远离箱体和须线，可能代表了一些异常值。

In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

#Define transformers for numerical and categorical columns
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='constant', fill_value='missing')),
    ('onehot', OneHotEncoder(handle_unknown='ignore',sparse_output=False))
])

创建两个转换器（transformer）来处理数值型和分类型变量，分别命名为numerical_transformer和categorical_transformer。这两个转换器都是使用Pipeline构建的，通过steps参数指定每个步骤的名称和要执行的操作。

numerical_transformer中的第一步是使用SimpleImputer类来填补缺失值。在这里，我们使用均值来填充缺失值，可以通过设置strategy参数为'mean'来实现。接下来，将使用StandardScaler类对所有的数值型特征进行标准化（Z-score标准化），以确保它们拥有相同的单位和范围。

categorical_transformer与numerical_transformer类似，但其处理的是分类型特征。在这里，将使用SimpleImputer填补缺失值，但这次采用常数填补法（constant，填补值为'missing'）。由于分类型特征不能直接输入模型中，因此，还要使用OneHotEncoder将分类型特征转换为二进制的数值型特征，即进行独热编码（One-Hot Encoding）。这可以通过将handle_unknown参数设置为'ignore', sparse参数设置为False 来实现。

使用ColumnTransformer将这两个转换器适当地应用到数据集中。可以使用remainder参数来指定如何处理没有被转换器覆盖的列。在这里，我们将其设置为'passthrough'以保留未被转换的列。

通过这些步骤，我们可以创建一个预处理管道，用于在训练和测试数据上执行对数据集的预处理。仅需定义这些pipeline 然后在数据上fit和transform 即可完成预处理。

In [22]:
#Update categorical and numerical columns
categorical_columns = df.select_dtypes(include=['object','category']).columns
numerical_columns = df.select_dtypes(include=['int64','float64']).columns

#Remove target variable from numerical columns
numerical_columns = numerical_columns.drop('SalePrice')

#Combine transformers using ColumnTransformer
preprocessor = ColumnTransformer(transformers=[
    ('num',numerical_transformer, numerical_columns),
    ('cat',categorical_transformer,categorical_columns)
],remainder = 'passthrough')

#Create a pipeline with the preprocessor
pipeline = Pipeline(steps=[
    ('preprocessor',preprocessor)
])

#Apply the pipeline to your dataset
X = df.drop('SalePrice', axis=1)
y = np.log(df['SalePrice'])  #normalize dependent variable
X_preprocessed = pipeline.fit_transform(X)

使用select_dtypes函数和include参数，将列类型限制为对象（object）和类别（category）的列，将列类型限制为整数（int64）和浮点数（float64）的列。然后，将结果分配给categorical_columns和numerical_columns变量。

从numerical_columns中移除目标变量（'SalePrice'），通过调用drop函数并将目标变量名称作为参数来实现。

使用ColumnTransformer将两个转换器（numerical_transformer和categorical_transformer）组合起来。这里使用了两个元组，第一个元组指定了数值列的步骤名称（'num'）、数值型转换器以及要应用转换器的数值列；第二个元组指定了分类型列的步骤名称（'cat'）、分类型转换器以及要应用转换器的分类型列。设置remainder参数为'passthrough'，以便保留没有被转换器覆盖的列。

创建一个Pipeline，其中包含preprocessor转换器。将该转换器命名为'preprocessor'。

将Pipeline应用于数据集。首先，将数据框X中的目标变量（'SalePrice'）从X中删除，得到新的数据框X（没有目标变量）。接下来，对目标变量进行对数变换，这可以通过使用np.log函数实现，然后将结果赋值给y。最后，使用Pipeline的fit_transform方法将preprocessor应用于X，得到经过预处理的数据集X_preprocessed。

通过这些步骤，你可以使用Pipeline对原始数据集进行预处理，获得经过转换和缺失值填补的特征矩阵X_preprocessed，以及经过对数变换的目标变量y。

In [23]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.model_selection import GridSearchCV, KFold, cross_val_score

# Check for CUDA support
try:
    import torch
    CUDA_AVAILABLE = torch.cuda.is_available()
    print(f"CUDA available: {CUDA_AVAILABLE}")
except ImportError:
    CUDA_AVAILABLE = False
    print("PyTorch not installed, using CPU for XGBoost")

#Split the data into training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_preprocessed, y, test_size=0.2, random_state=42)

#Define the models
models={
    'LinearRegression':LinearRegression(),
    'RandomForest':RandomForestRegressor(random_state=42),
    'XGBoost':XGBRegressor(random_state=42, tree_method='hist', device='cuda' if CUDA_AVAILABLE else 'cpu')
}

#Define the hyperparameter grids for each model
param_grids={
    'LinearRegression':{},
    'RandomForest':{
        'n_estimators':[100,200,500],
        'max_depth':[None,10,30],
        'min_samples_split':[2,5,10],
    },
    'XGBoost':{
        'n_estimators':[100,200,500],
        'learning_rate':[0.01,0.1,0.3],
        'max_depth':[3,6,10],
    }
}

#3-fold cross_validation
cv = KFold(n_splits=3, shuffle=True, random_state=42)

#Train and tune the models
grids = {}
for model_name, model in models.items():
    #print(f'Training and tuning {model_name}...')
    grids[model_name] = GridSearchCV(estimator=model, param_grid=param_grids[model_name], cv=cv, 
                                     scoring='neg_mean_squared_error', n_jobs=-1, verbose=2)
    grids[model_name].fit(X_train, y_train)
    best_params = grids[model_name].best_params_
    best_score = np.sqrt(-1 * grids[model_name].best_score_)
    
    print(f'Best parameters for {model_name}:{best_params}')
    print(f'Best RMSE for {model_name}:{best_score}\n')

CUDA available: True
Fitting 3 folds for each of 1 candidates, totalling 3 fits
Best parameters for LinearRegression:{}
Best RMSE for LinearRegression:0.17616568200328322

Fitting 3 folds for each of 27 candidates, totalling 81 fits
Best parameters for RandomForest:{'max_depth': None, 'min_samples_split': 2, 'n_estimators': 500}
Best RMSE for RandomForest:0.15332719681534118

Fitting 3 folds for each of 27 candidates, totalling 81 fits
Best parameters for XGBoost:{'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 500}
Best RMSE for XGBoost:0.13800996917288796

首先，将数据集划分为训练集和测试集，比例为80%的训练集和20%的测试集。

定义了一个字典models，包含了三个模型：线性回归（LinearRegression）、随机森林（RandomForestRegressor）和XGBoost（XGBRegressor）

定义了一个字典param_grids，包含了每个模型的超参数网格。对于线性回归，没有定义任何超参数；对于随机森林，定义了n_estimators、max_depth和min_samples_split；对于XGBoost，定义了n_estimators、learning_rate和max_depth。

创建了一个KFold对象，将数据集划分为3折交叉验证集。

对于每个模型，创建了一个GridSearchCV对象，将模型、超参数网格、交叉验证对象等作为参数传入。设置了scoring参数为'neg_mean_squared_error'，使用均方根误差（RMSE）作为评分指标。设置了n_jobs参数为-1，以便使用所有可用的CPU进行并行计算。设置了verbose参数为2，以便输出详细的训练信息。

调用GridSearchCV对象的fit方法，在训练集上进行网格搜索和交叉验证。通过调用best_params_属性和best_score_属性，获取最佳超参数和最佳RMSE值。

打印出每个模型的最佳超参数和最佳RMSE值。（RMSE值越小代表模型拟合效果越好，模型的预测结果也越准确）

整段代码的意义在于通过自动化的方式探索不同模型及其超参数组合的性能，以帮助选择最佳的模型和超参数配置。通过对不同模型的比较评估，可以找到在训练数据上表现最好的模型，并使用其最佳超参数配置进行后续预测任务。这有助于提高预测精度并优化模型性能。

In [24]:

from sklearn.neural_network import MLPRegressor

X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

# Create an MLPRegressor instance
mlp = MLPRegressor(random_state=42,max_iter=10000, n_iter_no_change = 3,learning_rate_init=0.001)

# Define the parameter grid for tuning
param_grid = {
    'hidden_layer_sizes': [(10,), (10,10), (10,10,10), (25)],
    'activation': ['relu', 'tanh'],
    'solver': ['adam'],
    'alpha': [0.0001, 0.001, 0.01],
    'learning_rate': ['constant', 'invscaling', 'adaptive'],
}

# Create the GridSearchCV object
grid_search_mlp = GridSearchCV(mlp, param_grid, scoring='neg_mean_squared_error', cv=3, n_jobs=-1, verbose=1)

# Fit the model on the training data
grid_search_mlp.fit(X_train_scaled, y_train)

# Print the best parameters found during the search
print("Best parameters found: ", grid_search_mlp.best_params_)

# Evaluate the model on the test data
best_score = np.sqrt(-1 * grid_search_mlp.best_score_)
print("Test score: ", best_score)

Fitting 3 folds for each of 72 candidates, totalling 216 fits

Best parameters found:  {'activation': 'relu', 'alpha': 0.001, 'hidden_layer_sizes': (10, 10), 'learning_rate': 'constant', 'solver': 'adam'}
Test score:  0.22778267781613568

导入MLPRegressor类，它是多层感知机（MLP）回归模型的实现类。

这两行代码将训练集和测试集的数据进行复制，分别存储在X_train_scaled和X_test_scaled变量中。这是为了后续对数据进行标准化处理时不改变原始数据。

设置一个MLPRegressor模型实例mlp，其中的参数有：
random_state：随机种子，用于保证模型的可重复性。
max_iter：最大迭代次数，控制模型的训练轮数。
n_iter_no_change：当连续n次迭代后模型性能没有显著提高时，停止迭代。
learning_rate_init：学习率的初始值，用于控制模型参数的更新速度。

定义了一个超参数网格param_grid，包含了多个超参数及其候选值。这些超参数包括：
hidden_layer_sizes：隐藏层的神经元数量和层数的组合。
activation：激活函数的选择，可以是ReLU或tanh。
solver：求解器的选择，这里选择了Adam优化器。
alpha：正则化系数的候选值。
learning_rate：学习率的调整方式，包括常数、递减和自适应。

创建了一个GridSearchCV类的实例对象grid_search_mlp，用于进行超参数搜索和模型评估。其中的参数有：
mlp：被搜索的模型对象。
param_grid：超参数网格。
scoring：评估指标，这里采用负均方误差（neg_mean_squared_error）作为损失函数。
cv：交叉验证的折数。
n_jobs：并行任务的数量，设置为-1表示使用所有可用的CPU核心。
verbose：详细输出。

在训练集上训练模型。GridSearchCV将尝试所有可能的组合，并根据指定的评分标准计算每个超参数组合下的平均性能。

打印最佳超参数组合

多层感知机（MLP）是一种经典的神经网络模型，由输入层、若干个隐含层和输出层构成。每个神经元接收来自上一层的输入，并通过激活函数对输入进行加权求和，最终得到输出。在回归任务中，MLPRegressor类可以通过权衡多个隐藏层、每层的神经元数量、激活函数、求解器类型、正则化系数和学习率等超参数，来优化模型的性能表现。GridSearchCV类则可以用来自动搜索最佳超参数组合与评估不同超参数下模型的性能表现。

In [25]:
#pca
from sklearn.decomposition import PCA

pca = PCA()
X_pca_pre = pca.fit_transform(X_preprocessed)

#Caculate the cmulative explained variance
cumulative_explained_variance = np.cumsum(pca.explained_variance_ratio_)

#Choose the number of components based on the explained variance threshold
n_components = np.argmax(cumulative_explained_variance >= 0.95) + 1

pca = PCA(n_components=n_components)
pipeline_pca = Pipeline(steps=
                       [('preprocessoe', preprocessor),
                       ('pca',pca)])
X_pca = pipeline_pca.fit_transform(X)

这行代码导入了sklearn库中的PCA类，用于进行主成分分析。

创建了一个PCA类的实例对象pca，并调用fit_transform()方法对经过预处理后的数据X_preprocessed进行主成分分析。该方法将返回降维后的数据X_pca_pre。

计算了累计解释方差。explained_variance_ratio_属性表示每个主成分解释的方差比例，通过np.cumsum()函数对其进行累计求和，得到每个主成分解释方差的累积值。

选择降维后保留的主成分数量。根据累计解释方差大于等于0.95的条件，使用np.argmax()函数找到第一个满足条件的索引，并加1得到主成分的数量。我们希望选择尽可能少的主成分来达到降维的目标，同时保留足够的数据信息。一种常用的选择方法是设定一个阈值，比如0.95，表示希望保留至少95%的原始数据方差。

重新创建一个PCA实例对象pca，将降维后保留的主成分数量作为参数传入。然后，构建了一个Pipeline对象pipeline_pca，其中包含预处理器和PCA模型，按照先预处理后进行PCA的顺序组成。最后，调用fit_transform()方法对原始数据X进行预处理和主成分分析，得到降维后的数据X_pca。

通过以上代码，你可以实现对数据进行PCA降维处理，并选择保留多少个主成分来达到一定的解释方差阈值。降维后的数据可以在X_pca中使用。

In [26]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.model_selection import GridSearchCV, KFold, cross_val_score

# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train_pca, X_test_pca, y_train_pca, y_test_pca = train_test_split(X_pca, y, test_size=0.2, random_state=42)

# Define the models
models = {
    'LinearRegression': LinearRegression(),
    'RandomForest': RandomForestRegressor(random_state=42),
    'XGBoost': XGBRegressor(random_state=42, tree_method='hist', device='cuda' if CUDA_AVAILABLE else 'cpu')
}

# Define the hyperparameter grids for each model
param_grids = {
    'LinearRegression': {},
    'RandomForest': {
        'n_estimators': [100, 200, 500],
        'max_depth': [None, 10, 30],
        'min_samples_split': [2, 5, 10],
    },
    'XGBoost': {
        'n_estimators': [100, 200, 500],
        'learning_rate': [0.01, 0.1, 0.3],
        'max_depth': [3, 6, 10],
    }
}

# 3-fold cross-validation
cv = KFold(n_splits=3, shuffle=True, random_state=42)

# Train and tune the models
grids_pca = {}
for model_name, model in models.items():
    #print(f'Training and tuning {model_name}...')
    grids_pca[model_name] = GridSearchCV(estimator=model, param_grid=param_grids[model_name], cv=cv, scoring='neg_mean_squared_error', n_jobs=-1, verbose=2)
    grids_pca[model_name].fit(X_train_pca, y_train_pca)
    best_params = grids_pca[model_name].best_params_
    best_score = np.sqrt(-1 * grids_pca[model_name].best_score_)
    
    print(f'Best parameters for {model_name}: {best_params}')
    print(f'Best RMSE for {model_name}: {best_score}\n')

Fitting 3 folds for each of 1 candidates, totalling 3 fits
Best parameters for LinearRegression: {}
Best RMSE for LinearRegression: 0.16321043786976014

Fitting 3 folds for each of 27 candidates, totalling 81 fits
Best parameters for RandomForest: {'max_depth': None, 'min_samples_split': 5, 'n_estimators': 500}
Best RMSE for RandomForest: 0.15183742282255228

Fitting 3 folds for each of 27 candidates, totalling 81 fits

d:\ProgramData\anaconda3\envs\py310\lib\site-packages\joblib\externals\loky\process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Best parameters for XGBoost: {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 500}
Best RMSE for XGBoost: 0.13619654261558312

代码通过指定数据集的训练集和测试集的划分比例，使用train_test_split函数将数据集X_pca和y划分为训练集和测试集。划分比例为0.2，即80%的数据作为训练集，20%的数据作为测试集。

自变量是pca处理过的x，因变量还是y

In [27]:
from sklearn.neural_network import MLPRegressor

X_train_scaled_pca = X_train_pca.copy()
X_test_scaled_pca = X_test_pca.copy()

#Create an MLPRegressor instance
mlp = MLPRegressor(random_state=42, max_iter=10000, n_iter_no_change = 3,learning_rate_init=0.001)

#Define the parameter grid for tuning
param_grid = {
    'hidden_layer_sizes':[(10,),(10,10),(10,10,10),(25)],
    'activation':['relu','tanh'],
    'solver':['adam'],
    'alpha':[0.0001, 0.001, 0.01, .1, 1],
    'learning_rate':['constant','invscaling','adaptive'],
}

#Create the GridSearchCV object
grid_search_mlp_pca = GridSearchCV(mlp, param_grid, scoring='neg_mean_squared_error',cv=3,n_jobs=-1,verbose=1)


#Fit the model on the training data
grid_search_mlp_pca.fit(X_train_scaled_pca, y_train)

#Print the best parameters found during the search
print('Best parameters found:', grid_search_mlp_pca.best_params_)

#Evaluate the model on the test data
best_score = np.sqrt(-1*grid_search_mlp_pca.best_score_)
print('Test score:',best_score)

Fitting 3 folds for each of 120 candidates, totalling 360 fits

Best parameters found: {'activation': 'tanh', 'alpha': 1, 'hidden_layer_sizes': (10, 10, 10), 'learning_rate': 'constant', 'solver': 'adam'}
Test score: 0.2186430133340787


自变量是pca处理过的x，因变量还是y，其他一致

In [28]:
from sklearn.metrics import mean_squared_error
for i in grids.keys():
    print(i + ':' + str(np.sqrt(mean_squared_error(grids[i].predict(X_test),y_test))))

LinearRegression:0.13212453580847502
RandomForest:0.1468371013683763
XGBoost:0.13502482143293712

d:\ProgramData\anaconda3\envs\py310\lib\site-packages\xgboost\core.py:751: UserWarning: [23:35:08] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\common\error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)

通过for循环遍历grids字典中存储的每个模型的网格搜索对象

i 是循环变量，代表当前迭代中所遍历的模型名称。

grids[i].predict(X_test) 使用网格搜索得到的最佳模型对测试集数据 X_test 进行预测，得到预测值。

mean_squared_error(grids[i].predict(X_test), y_test) 使用真实的目标值 y_test 和模型预测的目标值之间的平均偏差大小来计算均方根误差（RMSE）。


np.sqrt(mean_squared_error(grids[i].predict(X_test), y_test)) 使用 numpy 库中的 sqrt 函数对均方根误差进行开方，以得到更直观的误差值。

str(np.sqrt(mean_squared_error(grids[i].predict(X_test), y_test))) 将得到的均方根误差转换为字符串形式。

i + ':' + str(np.sqrt(mean_squared_error(grids[i].predict(X_test), y_test))) 将模型名称和对应的均方根误差拼接成一个字符串，并打印输出。

这段代码的作用是使用测试集数据来评估训练好的模型在新数据上的表现，以了解模型的泛化能力。对于每个模型，使用均方根误差（RMSE）来量化预测误差，并将其打印输出以进行模型比较。

测试对象是每个模型的X_test

In [29]:
from sklearn.metrics import mean_squared_error
for i in grids.keys():
    print (i + ': ' + str(np.sqrt(mean_squared_error(grids_pca[i].predict(X_test_pca), y_test))))

LinearRegression: 0.1420250969020267
RandomForest: 0.15246630846623355
XGBoost: 0.14001940235638602

测试对象是3个模型的X_test_pca，其余一样

输出3个模型pca处理过的RMSE值

In [30]:
print( str(np.sqrt(mean_squared_error(grid_search_mlp.predict(X_test_scaled),y_test))))

0.1668391027224058

使用了另外一个模型 grid_search_mlp，对测试数据集 X_test_scaled 进行预测，并计算预测值和真实值之间的均方根误差（RMSE）。

In [31]:
print( str(np.sqrt(mean_squared_error(grid_search_mlp_pca.predict(X_test_scaled_pca), y_test))))

0.18271928755021824

使用了经过 PCA（主成分分析）处理后的测试集数据 X_test_scaled_pca。

使用了另一个模型 grid_search_mlp_pca，该模型是在 PCA 处理后的数据上训练的。

In [32]:
var_explore = df[['Fence','Alley','MiscFeature','PoolQC','FireplaceQu','GarageCond','GarageQual','GarageFinish','GarageType','BsmtExposure','BsmtFinType2','BsmtFinType1','BsmtCond','BsmtQual','MasVnrType','Electrical','MSZoning','Utilities','Exterior1st','Exterior2nd','KitchenQual','Functional','SaleType','LotFrontage','GarageYrBlt','MasVnrArea','BsmtFullBath','BsmtHalfBath','GarageCars','GarageArea','TotalBsmtSF']]

display(HTML(create_scrollable_table(var_explore, 'var_explore', 'List of Variables to Explore for Feature Engineering')))

df[['Fence','Alley','MiscFeature',...,'GarageArea','TotalBsmtSF']] 使用双方括号，选择了 DataFrame 数据中的多个列，这些列名分别为 'Fence', 'Alley', 'MiscFeature', ... , 'GarageArea', 'TotalBsmtSF'。

display(HTML(create_scrollable_table(var_explore, 'var_explore', 'List of Variables to Explore for Feature Engineering'))) 该行代码将选择的数据表格使用 create_scrollable_table 函数转换为 HTML 表格，并通过 display(HTML(...)) 函数显示在网页上。其中，'var_explore' 是 HTML 表格的 id，用于后续的 CSS 样式调整。'List of Variables to Explore for Feature Engineering' 是表格的标题。

最终的输出结果是一个包含了所选特征变量的可滚动 HTML 表格，方便展示和探索这些变量的数据分布和统计信息。

In [33]:
from sklearn.preprocessing import FunctionTransformer

# feature engineering functions 
def custom_features(df):
    df_out = df.copy()
    df_out['PropertyAge'] = df_out['YrSold'] - df_out['YearBuilt']
    df_out['TotalSF'] = df_out['TotalBsmtSF'] + df_out['1stFlrSF'] + df_out['2ndFlrSF']
    df_out['TotalBath'] = df_out['FullBath'] + 0.5 * df_out['HalfBath'] + df_out['BsmtFullBath'] + 0.5 * df['BsmtHalfBath']
    df_out['HasRemodeled'] = (df_out['YearRemodAdd'] != df_out['YearBuilt']).astype(object)
    df_out['Has2ndFloor'] = (df_out['2ndFlrSF'] > 0).astype(object)
    df_out['HasGarage'] = (df_out['GarageArea'] > 0).astype(object)
    df_out['YrSold_cat'] = df_out['YrSold'].astype(object)
    df_out['MoSold_cat'] = df_out['MoSold'].astype(object)
    df_out['YearBuilt_cat'] = df_out['YearBuilt'].astype(object)
    df_out['MSSubClass_cat'] = df_out['MSSubClass'].astype(object)
    
    return df_out

feature_engineering_transformer = FunctionTransformer(custom_features)


#make this better, one functtion? get new variables in the pipeline?

custom_features(df) 是一个自定义的特征工程函数，接受一个 DataFrame df 作为输入，并对其进行一系列操作和变换，生成新的特征，并返回处理后的 DataFrame df_out。

计算房屋的 PropertyAge 特征，即当前年份 'YrSold' 减去建房年份 'YearBuilt'。

计算总面积特征 TotalSF，即地下室面积 'TotalBsmtSF' 加上一楼面积 '1stFlrSF' 和二楼面积 '2ndFlrSF' 的和。

计算总浴室数量特征 TotalBath，其中包括全浴室数量 'FullBath'、半浴室数量 'HalfBath'（乘以 0.5 来表示），地下室全浴室数量 'BsmtFullBath' 和地下室半浴室数量 'BsmtHalfBath'（乘以 0.5）的总和。

创建布尔特征 HasRemodeled，判断是否进行过房屋翻新，即 'YearRemodAdd' 是否与 'YearBuilt' 不相等，并将其转换为对象类型（object）。

创建布尔特征 Has2ndFloor，判断是否有二楼，即二楼面积 '2ndFlrSF' 是否大于 0，并将其转换为对象类型（object）。

创建布尔特征 HasGarage，判断是否有车库，即车库面积 'GarageArea' 是否大于 0，并将其转换为对象类型（object）。

将年份特征 'YrSold'、'MoSold'、'YearBuilt' 和 'MSSubClass' 转换为对象类型（object），以便后续处理。

feature_engineering_transformer = FunctionTransformer(custom_features) 使用 FunctionTransformer 将自定义的特征工程函数 custom_features 转换为可用于机器学习流水线的转换器 feature_engineering_transformer。

最后一条注释中提到了对代码进行进一步优化的可能性，具体优化方式需要根据实际情况和需求进一步考虑，比如将生成新特征的步骤整合到机器学习流水线中，以提高代码的整体性能和可读性。

In [34]:
# Identify categorical and numerical columns
new_cols_categorical = pd.Index(['HasRemodeled', 'Has2ndFloor', 'HasGarage'])
new_cols_numeric = pd.Index(['PropertyAge', 'TotalSF', 'TotalBath', 'YrSold_cat', 'MoSold_cat', 'YearBuilt_cat', 'MSSubClass_cat'])

# Update categorical and numerical columns
categorical_columns = df.select_dtypes(include=['object', 'category']).columns.append(new_cols_categorical)
numerical_columns = df.select_dtypes(include=['int64', 'float64']).columns.append(new_cols_numeric)

# Remove target variable from numerical columns
numerical_columns = numerical_columns.drop('SalePrice')

# Combine transformers using ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_columns),
        ('cat', categorical_transformer, categorical_columns)
    ],remainder = 'passthrough')

# Create a pipeline with the preprocessor
pipeline_fe = Pipeline(steps=[
    ('fe', feature_engineering_transformer),
    ('preprocessor', preprocessor),
    ('pca', pca)])

# Apply the pipeline to your dataset
X = df.drop('SalePrice', axis=1)
y = np.log(df['SalePrice'])
X_preprocessed_fe = pipeline_fe.fit_transform(X)

new_cols_categorical 是一个包含新分类列的索引，这些列是在特征工程中生成的。

new_cols_numeric 是一个包含新数值列的索引，这些列也是在特征工程中生成的。

categorical_columns 是包含所有分类列的索引，其中包括原始数据集中的分类列和新生成的分类列。

numerical_columns 是包含所有数值列的索引，其中包括原始数据集中的数值列和新生成的数值列。

将目标变量从数值列中删除，得到更新后的数值列索引 numerical_columns。

使用 ColumnTransformer 将转换器组合在一起。preprocessor 包含两个转换器：'num' 转换器使用 numerical_transformer 对数值列进行转换，'cat' 转换器使用 categorical_transformer 对分类列进行转换。同时，设
置 remainder='passthrough'，以保留未被转换的其他列。

创建一个包含特征工程的流水线 pipeline_fe，它包括三个步骤：特征工程转换器 feature_engineering_transformer、预处理器 preprocessor 和 PCA（主成分分析）。

将流水线应用于数据集。首先从数据集中去除目标变量 SalePrice，然后对样本使用流水线进行特征提取和预处理，得到转换后的数据集 X_preprocessed_fe。同时，将目标变量 SalePrice 取对数，存储在变量 y 中。

In [35]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train_fe, X_test_fe, y_train_fe, y_test_fe = train_test_split(X_preprocessed_fe, y, test_size=0.2, random_state=42)

# Define the models
models = {
    'LinearRegression': LinearRegression(),
    'RandomForest': RandomForestRegressor(random_state=42),
    'XGBoost': XGBRegressor(random_state=42, tree_method='hist', device='cuda' if CUDA_AVAILABLE else 'cpu')
}

# Define the hyperparameter grids for each model
param_grids = {
    'LinearRegression': {},
    'RandomForest': {
        'n_estimators': [100, 200, 500],
        'max_depth': [None, 10, 30],
        'min_samples_split': [2, 5, 10],
    },
    'XGBoost': {
        'n_estimators': [100, 200, 500],
        'learning_rate': [0.01, 0.1, 0.3],
        'max_depth': [3, 6, 10],
    }
}

# 3-fold cross-validation
cv = KFold(n_splits=3, shuffle=True, random_state=42)

# Train and tune the models
grids_fe = {}
for model_name, model in models.items():
    #print(f'Training and tuning {model_name}...')
    grids_fe[model_name] = GridSearchCV(estimator=model, param_grid=param_grids[model_name], cv=cv, scoring='neg_mean_squared_error', n_jobs=-1, verbose=2)
    grids_fe[model_name].fit(X_train_fe, y_train_fe)
    best_params = grids_fe[model_name].best_params_
    best_score = np.sqrt(-1 * grids_fe[model_name].best_score_)
    
    print(f'Best parameters for {model_name}: {best_params}')
    print(f'Best RMSE for {model_name}: {best_score}\n')

Fitting 3 folds for each of 1 candidates, totalling 3 fits
Best parameters for LinearRegression: {}
Best RMSE for LinearRegression: 0.164153675964183

Fitting 3 folds for each of 27 candidates, totalling 81 fits
Best parameters for RandomForest: {'max_depth': None, 'min_samples_split': 5, 'n_estimators': 500}
Best RMSE for RandomForest: 0.15059299019430233

Fitting 3 folds for each of 27 candidates, totalling 81 fits
Best parameters for XGBoost: {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 500}
Best RMSE for XGBoost: 0.13668656572396598

与之前的3个模型代码一致，只是变量变成了fe和pca过的数据X_fe

In [36]:
X_train_scaled_fe = X_train_fe.copy()
X_test_scaled_fe = X_test_fe.copy()

# Create an MLPRegressor instance
from sklearn.neural_network import MLPRegressor

mlp = MLPRegressor(random_state=42, max_iter=10000, n_iter_no_change=3)

# Define the parameter grid for tuning
param_grid = {
    'hidden_layer_sizes': [(10,), (10, 10), (10, 25)],
    'activation': ['relu', 'tanh', 'sigmoid'],
    'solver': ['adam', 'sgd'],
    'alpha': [.1, .5, 1, 10, 100],
    'learning_rate': ['constant', 'invscaling', 'adaptive'],
    'learning_rate_init' : [0.1]
}

# Create the GridSearchCV object
from sklearn.model_selection import GridSearchCV
grid_search_mlp_fe = GridSearchCV(mlp, param_grid, scoring='neg_mean_squared_error', cv=3, n_jobs=-1, verbose=1)

# Fit the model on the training data
grid_search_mlp_fe.fit(X_train_scaled_fe, y_train_fe)

# Print the best parameters found during the search
print("Best parameters found: ", grid_search_mlp_fe.best_params_)

# Evaluate the model on the test data
best_score = np.sqrt(-1 * grid_search_mlp_fe.best_score_)
print("Test score: ", best_score)

Fitting 3 folds for each of 270 candidates, totalling 810 fits

d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
324 fits failed out of a total of 810.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
54 fits failed with the following error:
Traceback (most recent call last):
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py", line 849, in fit
    return self._fit(X, y, sample_weight=sample_weight, incremental=False)
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py", line 536, in _fit
    raise ValueError(
ValueError: Solver produced non-finite parameter weights. The input data may contain large values and need to be preprocessed.

--------------------------------------------------------------------------------
57 fits failed with the following error:
Traceback (most recent call last):
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'activation' parameter of MLPRegressor must be a str among {'logistic', 'identity', 'tanh', 'relu'}. Got 'sigmoid' instead.

--------------------------------------------------------------------------------
53 fits failed with the following error:
Traceback (most recent call last):
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'activation' parameter of MLPRegressor must be a str among {'identity', 'tanh', 'relu', 'logistic'}. Got 'sigmoid' instead.

--------------------------------------------------------------------------------
47 fits failed with the following error:
Traceback (most recent call last):
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'activation' parameter of MLPRegressor must be a str among {'relu', 'identity', 'logistic', 'tanh'}. Got 'sigmoid' instead.

--------------------------------------------------------------------------------
44 fits failed with the following error:
Traceback (most recent call last):
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'activation' parameter of MLPRegressor must be a str among {'logistic', 'identity', 'relu', 'tanh'}. Got 'sigmoid' instead.

--------------------------------------------------------------------------------
26 fits failed with the following error:
Traceback (most recent call last):
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'activation' parameter of MLPRegressor must be a str among {'tanh', 'identity', 'logistic', 'relu'}. Got 'sigmoid' instead.

--------------------------------------------------------------------------------
21 fits failed with the following error:
Traceback (most recent call last):
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'activation' parameter of MLPRegressor must be a str among {'relu', 'tanh', 'identity', 'logistic'}. Got 'sigmoid' instead.

--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'activation' parameter of MLPRegressor must be a str among {'logistic', 'relu', 'identity', 'tanh'}. Got 'sigmoid' instead.

--------------------------------------------------------------------------------
9 fits failed with the following error:
Traceback (most recent call last):
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'activation' parameter of MLPRegressor must be a str among {'tanh', 'logistic', 'relu', 'identity'}. Got 'sigmoid' instead.

--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
  File "d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'activation' parameter of MLPRegressor must be a str among {'tanh', 'logistic', 'identity', 'relu'}. Got 'sigmoid' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
d:\ProgramData\anaconda3\envs\py310\lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [-1.63007666e+00             nan -1.63007666e+00             nan
 -1.63007666e+00             nan -9.38740370e-01 -6.14128245e+00
 -9.38740370e-01 -1.00235725e+03 -9.38740370e-01 -9.25049754e-01
 -9.70327840e-02 -2.57131472e+06 -9.70327840e-02 -1.56920712e+01
 -9.70327840e-02 -1.65245353e+05 -1.06608480e+00             nan
 -1.06608480e+00             nan -1.06608480e+00             nan
 -5.68925480e-01 -8.24663779e+04 -5.68925480e-01 -1.08845866e+03
 -5.68925480e-01 -5.03736937e+03 -3.07961862e-02 -6.89123179e+01
 -3.07961862e-02 -5.71713439e+01 -3.07961862e-02 -2.94690071e-01
 -8.94926197e-01             nan -8.94926197e-01             nan
 -8.94926197e-01             nan -4.23383619e-01 -1.05349004e+05
 -4.23383619e-01 -1.09290733e+03 -4.23383619e-01 -6.48293062e+03
 -2.60945655e-02 -2.82845291e+00 -2.60945655e-02 -4.76795275e+01
 -2.60945655e-02 -4.11443556e-01 -4.93104902e-01             nan
 -4.93104902e-01             nan -4.93104902e-01             nan
 -4.13462032e-02 -2.28746477e+04 -4.13462032e-02 -1.05351771e+03
 -4.13462032e-02 -4.56102298e+03 -2.96428756e-02 -4.16587898e+24
 -2.96428756e-02 -5.89186087e+01 -2.96428756e-02 -2.55459972e+32
 -4.93770625e-02             nan -4.93770625e-02             nan
 -4.93770625e-02             nan -1.14045497e-01             nan
 -1.14045497e-01 -1.72331269e+04 -1.14045497e-01             nan
 -9.41919201e-02             nan -9.41919201e-02 -2.41554861e+01
 -9.41919201e-02             nan -1.84772364e+00 -3.25810052e-02
 -1.84772364e+00 -2.80196041e+01 -1.84772364e+00 -3.18193301e-02
 -2.42841757e-02 -2.23640749e-02 -2.42841757e-02 -1.05917216e+00
 -2.42841757e-02 -2.22423116e-02 -2.79943901e-02 -4.75793780e+00
 -2.79943901e-02 -1.91350960e+00 -2.79943901e-02 -1.02903479e+00
 -9.90608756e-01 -1.93344687e-02 -9.90608756e-01 -2.78563380e+01
 -9.90608756e-01 -1.90747420e-02 -1.70486833e-02 -1.64440945e-02
 -1.70486833e-02 -1.03844478e+00 -1.70486833e-02 -1.63148245e-02
 -1.94977202e-02 -4.64822454e+00 -1.94977202e-02 -3.87053791e+00
 -1.94977202e-02 -8.41364362e-01 -6.40005194e-01 -2.76012014e-01
 -6.40005194e-01 -2.76530489e+01 -6.40005194e-01 -1.86717392e-02
 -1.72420551e-02 -1.71382230e-02 -1.72420551e-02 -1.01329145e+00
 -1.72420551e-02 -1.61889212e-02 -2.04382263e-02 -5.68487433e+00
 -2.04382263e-02 -3.71058507e+00 -2.04382263e-02 -5.56974160e-01
 -3.30324933e-02 -2.22017681e-02 -3.30324933e-02 -2.41369920e+01
 -3.30324933e-02 -2.20221492e-02 -3.64360024e-02 -2.73440802e-02
 -3.64360024e-02 -1.02842137e+00 -3.64360024e-02 -2.60729458e-02
 -3.42257960e-02 -1.00556348e+03 -3.42257960e-02 -3.04575906e+01
 -3.42257960e-02 -4.25387062e+01 -1.53115084e-01 -9.13773351e-02
 -1.53115084e-01 -1.02037515e+01 -1.53115084e-01 -8.95652018e-02
 -1.53751166e-01 -1.53621088e-01 -1.53751166e-01 -5.01333085e-01
 -1.53751166e-01 -1.53031132e-01 -1.78283420e-01 -1.46025861e+01
 -1.78283420e-01 -2.46590258e+01 -1.78283420e-01 -1.54188725e-01
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan             nan             nan
             nan             nan]
  warnings.warn(

Best parameters found:  {'activation': 'tanh', 'alpha': 1, 'hidden_layer_sizes': (10, 10), 'learning_rate': 'adaptive', 'learning_rate_init': 0.1, 'solver': 'sgd'}
Test score:  0.12723569139959653

与之前的MLP一致，只是数据变成了fe和pca过的X_fe

In [37]:
from sklearn.metrics import mean_squared_error
for i in grids.keys():
    print (i + ': ' + str(np.sqrt(mean_squared_error(grids_fe[i].predict(X_test_fe), y_test))))

LinearRegression: 0.1424064219761821
RandomForest: 0.15275989062227732
XGBoost: 0.13986755592807973

In [38]:
print( str(np.sqrt(mean_squared_error(grid_search_mlp_fe.predict(X_test_scaled_fe),y_test))))

0.13501400915677006

In [39]:
df_test = pd.read_csv('kaggle/input/house-prices-advanced-regression-techniques/test.csv')
df_test_preprocessed = pipeline_fe.transform(df_test)

In [40]:
#xgboost submission
y_xgboost = np.exp(grids_fe['XGBoost'].predict(df_test_preprocessed))

df_xgboost_out = df_test[['Id']].copy()
df_xgboost_out['SalePrice'] = y_xgboost

#
df_xgboost_out.to_csv('submission_xgboost_new_features_normalized.csv', index=False)

将id和XGBoost预测值组成一个两列的表格，输出为csv文件（选择的是fe和pca过的数据训练出来的那次模型）

In [41]:
df_xgboost_out

        Id      SalePrice
0     1461  124286.398438
1     1462  140409.281250
2     1463  188141.187500
3     1464  191873.000000
4     1465  166920.078125
...    ...            ...
1454  2915   88874.742188
1455  2916   84080.585938
1456  2917  157372.312500
1457  2918  118242.000000
1458  2919  208407.281250

[1459 rows x 2 columns]

In [42]:
#rf submission
y_rf = np.exp(grids_fe['RandomForest'].predict(df_test_preprocessed))

df_rf_out = df_test[['Id']].copy()
df_rf_out['SalePrice'] = y_rf

#
df_rf_out.to_csv('submission_rf_normalized.csv', index=False)

将id和RandomForest预测值组成一个两列的表格，输出为csv文件（选择的是fe和pca过的数据训练出来的那次模型）

In [43]:
df_rf_out

        Id      SalePrice
0     1461  121856.041596
1     1462  141829.206206
2     1463  186422.751049
3     1464  191782.220605
4     1465  183466.830190
...    ...            ...
1454  2915  100039.104313
1455  2916   95175.915867
1456  2917  166613.429249
1457  2918  122797.174916
1458  2919  211864.208647

[1459 rows x 2 columns]

In [44]:
#mlp submission
y_mlp = np.exp(grid_search_mlp_fe.predict(df_test_preprocessed))

df_mlp_out = df_test[['Id']].copy()
df_mlp_out['SalePrice'] = y_mlp

df_mlp_out.to_csv('submission_mlp_normalized.csv', index=False)

将id和MLP预测值组成一个两列的表格，输出为csv文件（选择的是fe和pca过的数据训练出来的那次模型）

In [45]:
df_mlp_out

        Id      SalePrice
0     1461  118067.797287
1     1462  158133.863170
2     1463  176534.083332
3     1464  195270.756032
4     1465  180616.584138
...    ...            ...
1454  2915   92249.374113
1455  2916   96105.575112
1456  2917  161878.858755
1457  2918  119899.786312
1458  2919  228608.095639

[1459 rows x 2 columns]

In [46]:
y_avg_ens = (y_rf + y_xgboost + y_mlp)/3

#xgboost submission
df_avg_ens_out = df_test[['Id']].copy()
df_avg_ens_out['SalePrice'] = y_avg_ens

#
df_avg_ens_out.to_csv('submission_avg_ens_new_features_normalized.csv', index=False)

将id和RF XGB MLP三个模型预测值的平均数组成一个两列的表格，输出为csv文件（选择的是fe和pca过的数据训练出来的那次模型）

In [47]:
df_avg_ens_out

        Id      SalePrice
0     1461  121403.412440
1     1462  146790.783542
2     1463  183699.340627
3     1464  192975.325545
4     1465  177001.164151
...    ...            ...
1454  2915   93721.073538
1455  2916   91787.358972
1456  2917  161954.866835
1457  2918  120312.987076
1458  2919  216293.195179

[1459 rows x 2 columns]

In [48]:
from sklearn.ensemble import StackingRegressor

grids_fe['MLP'] =   grid_search_mlp_fe

best_estimators = [(model_name, grid.best_estimator_) for model_name, grid in grids_fe.items()]

# Define the candidate meta-models
meta_models = {
    'MLP': MLPRegressor(random_state=42, max_iter=10000, n_iter_no_change=3, learning_rate_init=0.001),
    'LinearRegression': LinearRegression(),
    'XGBoost': XGBRegressor(random_state=42, tree_method='hist', device='cuda' if CUDA_AVAILABLE else 'cpu')
}

# Define the hyperparameter grids for each meta-model
meta_param_grids = {
    'MLP': {
        'final_estimator__hidden_layer_sizes': [(10,), (10, 10)],
        'final_estimator__activation': ['relu', 'tanh'],
        'final_estimator__solver': ['adam', 'sgd'],
        'final_estimator__alpha': [ 0.001, 0.01, .1, .5],
        'final_estimator__learning_rate': ['constant', 'invscaling', 'adaptive'],
    },
    'LinearRegression': {},
    'XGBoost': {
        'final_estimator__n_estimators': [100, 200, 500],
        'final_estimator__learning_rate': [0.01, 0.1, 0.3],
        'final_estimator__max_depth': [3, 6, 10],
    }
}

# 3-fold cross-validation
cv = KFold(n_splits=3, shuffle=True, random_state=42)

# Train and tune the stacking ensemble
best_score = float('inf')
best_model = None

for meta_name, meta_model in meta_models.items():
    print(f'Training and tuning {meta_name} as the meta-model...')
    stacking_regressor = StackingRegressor(estimators=best_estimators, final_estimator=meta_model, cv=cv)
    grid_search = GridSearchCV(estimator=stacking_regressor, param_grid=meta_param_grids[meta_name], cv=cv, scoring='neg_mean_squared_error', n_jobs=-1, verbose=1)
    grid_search.fit(X_train_fe, y_train_fe)
    best_params = grid_search.best_params_
    best_rmse = np.sqrt(-1 * grid_search.best_score_)
    
    print(f'Best parameters for {meta_name}: {best_params}')
    print(f'Best RMSE for {meta_name}: {best_rmse}\n')
    
    if best_rmse < best_score:
        best_score = best_rmse
        best_model = grid_search

# Evaluate the best stacking ensemble on the test data
y_pred = best_model.predict(X_test_fe)
rmse = np.sqrt(mean_squared_error(y_test_fe, y_pred))
print(f"Best stacking ensemble's RMSE on test data: {rmse}")

Training and tuning MLP as the meta-model...
Fitting 3 folds for each of 96 candidates, totalling 288 fits
Best parameters for MLP: {'final_estimator__activation': 'relu', 'final_estimator__alpha': 0.5, 'final_estimator__hidden_layer_sizes': (10,), 'final_estimator__learning_rate': 'adaptive', 'final_estimator__solver': 'sgd'}
Best RMSE for MLP: 0.13947396331799516

Training and tuning LinearRegression as the meta-model...
Fitting 3 folds for each of 1 candidates, totalling 3 fits
Best parameters for LinearRegression: {}
Best RMSE for LinearRegression: 0.14553438240550282

Training and tuning XGBoost as the meta-model...
Fitting 3 folds for each of 27 candidates, totalling 81 fits
Best parameters for XGBoost: {'final_estimator__learning_rate': 0.01, 'final_estimator__max_depth': 3, 'final_estimator__n_estimators': 500}
Best RMSE for XGBoost: 0.13444620027352883

Best stacking ensemble's RMSE on test data: 0.1370486694929713

定义了元模型候选列表 meta_models，其中包含了三个元模型：MLPRegressor、LinearRegression 和 XGBRegressor。

为每个元模型定义了相应的超参数网格 meta_param_grids，用于后续的网格搜索。每个元模型的超参数网格都可以根据需求进行自定义。

使用 KFold 创建了一个 3 折交叉验证对象 cv。

然后，开始训练和调优堆叠集成模型。对于每个元模型，依次进行如下操作：

创建一个 StackingRegressor 对象，并使用最佳基模型和当前元模型作为参数。

使用 GridSearchCV 进行网格搜索，通过交叉验证选择出最佳的超参数配置。在网格搜索过程中，使用了之前创建的交叉验证对象 cv。

输出当前元模型的最佳超参数和最佳均方根误差（负数形式）。

如果当前元模型的最佳均方根误差比之前的模型更好，更新最佳模型和最佳分数。

使用最佳模型在测试数据上进行预测，并计算预测结果与真实标签的均方根误差，并输出该结果。

在代码中使用了 best_estimators 来作为基模型列表，这个列表是之前代码中定义的最佳基模型的集合。

这段代码使用了StackingRegressor来构建一个堆叠集成模型，并通过网格搜索寻找最佳超参数配置。

训练三个模型，并选出最好的。

In [49]:
y_stack = np.exp(best_model.predict(df_test_preprocessed))

#xgboost submission

df_stack_out = df_test[['Id']].copy()
df_stack_out['SalePrice'] = y_stack

df_stack_out.to_csv('submission_stack_new_features_normalized.csv', index=False)

将id和堆叠比较中最好的模型的预测值组成一个两列的表格，输出为csv文件（选择的是fe和pca过的数据训练出来的那次模型）

In [50]:
df_stack_out

        Id      SalePrice
0     1461  120745.335938
1     1462  152692.312500
2     1463  179104.046875
3     1464  190645.078125
4     1465  176807.218750
...    ...            ...
1454  2915   91434.046875
1455  2916   91350.812500
1456  2917  160397.390625
1457  2918  123039.140625
1458  2919  222504.812500

[1459 rows x 2 columns]

In [51]:
df_stack_out.to_csv('submission.csv', index=False)